- frontend/src/routes/settings/account/account-form.svelte
- frontend/src/routes/settings/admin/users/user-form.svelte
- frontend/tests/account-settings.spec.ts
- frontend/tests/user-settings.spec.ts
Added spaces between first/last and name in the application configuration
> Edit first and last name labels

- .github/ISSUE_TEMPLATE/bug.yml
Updating the bug issue template to request more info like log files, Pocket ID version, Reverse Proxy etc.
> refactor: bug template update

- docs/docs/client-examples/proxmox.md
Corrected some typos in the proxmox.md file for configuring Proxmox with Pocket ID.
> docs: fix typos and improve clarity in proxmox.md

- docs/docs/client-examples/headscale.md
- docs/docs/client-examples/immich.md
- docs/sidebars.ts
Added documentation for setting up Immich and Headscale.
> docs: Add Immich and Headscale client examples

- docs/docs/client-examples/gitea.md
- docs/docs/client-examples/memos.md
- docs/sidebars.ts
Added examples for Gitea and Memos. 
Your project is great!
> docs: Added Gitea and Memos example

- docs/docs/setup/installation.md
For proxmox users this script can easily setup a LXC container with pocket id installed.
> docs: add helper scripts install for proxmox

- backend/internal/common/errors.go
- backend/internal/controller/oidc_controller.go
- backend/internal/dto/oidc_dto.go
- backend/internal/dto/user_group_dto.go
- backend/internal/model/oidc.go
- backend/internal/service/oidc_service.go
- backend/internal/service/test_service.go
- backend/resources/migrations/postgres/20250131154719_oidc_user_group_restriction.down.sql
- backend/resources/migrations/postgres/20250131154719_oidc_user_group_restriction.up.sql
- backend/resources/migrations/sqlite/20250131154719_oidc_user_group_restriction.down.sql
- backend/resources/migrations/sqlite/20250131154719_oidc_user_group_restriction.up.sql
- frontend/src/lib/components/collapsible-card.svelte
- frontend/src/lib/components/ui/card/card-description.svelte
- frontend/src/lib/services/oidc-service.ts
- frontend/src/lib/types/oidc.type.ts
- frontend/src/routes/authorize/+page.svelte
- frontend/src/routes/authorize/components/client-provider-images.svelte
- frontend/src/routes/settings/admin/application-configuration/+page.svelte
- frontend/src/routes/settings/admin/oidc-clients/[id]/+page.svelte
- frontend/src/routes/settings/admin/oidc-clients/oidc-client-form.svelte
- frontend/src/routes/settings/admin/oidc-clients/user-group-selection.svelte
- frontend/src/routes/settings/admin/user-groups/[id]/+page.svelte
- frontend/src/routes/settings/admin/user-groups/user-group-list.svelte
- frontend/src/routes/settings/admin/users/[id]/+page.svelte
- frontend/tests/account-settings.spec.ts
- frontend/tests/application-configuration.spec.ts
- frontend/tests/oidc.spec.ts
- frontend/tests/user-group.spec.ts
- frontend/tests/user-settings.spec.ts
- frontend/tests/utils/passkey.util.ts
> feat: map allowed groups to OIDC clients

- backend/internal/dto/app_config_dto.go
- backend/internal/model/app_config.go
- backend/internal/service/app_config_service.go
- backend/internal/service/ldap_service.go
- frontend/src/lib/types/application-configuration.ts
- frontend/src/routes/settings/admin/application-configuration/forms/app-config-ldap-form.svelte
- frontend/tests/application-configuration.spec.ts
This will fix https://github.com/pocket-id/pocket-id/issues/215
> feat: ldap search filters

- frontend/package-lock.json
- frontend/src/routes/settings/admin/user-groups/user-group-list.svelte
- frontend/src/routes/settings/admin/users/user-list.svelte
This adds a simple badge that shows the source of the user or group in the list table.
> feat: user/group source location badge

- backend/internal/dto/app_config_dto.go
- backend/internal/service/app_config_service.go
- backend/internal/service/email_service.go
- backend/resources/migrations/postgres/20250225182112_manual_smtp_tls_selection.down.sql
- backend/resources/migrations/postgres/20250225182112_manual_smtp_tls_selection.up.sql
- backend/resources/migrations/sqlite/20250225182112_manual_smtp_tls_selection.down.sql
- backend/resources/migrations/sqlite/20250225182112_manual_smtp_tls_selection.up.sql
- frontend/package-lock.json
- frontend/src/lib/types/application-configuration.ts
- frontend/src/routes/settings/admin/application-configuration/forms/app-config-email-form.svelte
Fixes: https://github.com/pocket-id/pocket-id/issues/264
I tested and this works, but could maybe be cleaner, or some stuff could be changed a bit.
> fix: add option to manually select SMTP TLS method

- backend/go.mod
- backend/go.sum
- backend/internal/service/email_service.go
> fix: support `LOGIN` authentication method for SMTP

- .github/workflows/build-and-push-docker-image.yml
- .github/workflows/pr-docker-build.yml
Add a WF to build a docker image on each pull request. May need aditional tweaks.
> ci/cd: add pr docker build

- frontend/src/routes/settings/admin/oidc-clients/+page.server.ts
- frontend/src/routes/settings/admin/oidc-clients/oidc-client-list.svelte
- frontend/src/routes/settings/admin/user-groups/+page.server.ts
- frontend/src/routes/settings/admin/user-groups/user-group-list.svelte
- frontend/src/routes/settings/admin/user-groups/user-selection.svelte
- frontend/src/routes/settings/admin/users/+page.server.ts
- frontend/src/routes/settings/admin/users/user-list.svelte
Fixes: https://github.com/pocket-id/pocket-id/issues/298
> fix: default sorting on tables

- frontend/src/routes/settings/account/+page.svelte
> fix: typo in account settings

- .devcontainer/devcontainer.json
- .github/dependabot.yml
- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- CONTRIBUTING.md
Idea is that this will simplify + standardize dev environment setup. 
Additionally, it'll lower the barrier to entry for new contributors with easy setup and debug options.
> chore: add Dev Container

- backend/resources/email-templates/login-with-new-device_html.tmpl
- backend/resources/email-templates/one-time-access_html.tmpl
Fixes: https://github.com/pocket-id/pocket-id/issues/334
> fix: email logo icon displaying too big

- frontend/src/lib/components/header/header-avatar.svelte
~~#331~~ https://github.com/pocket-id/pocket-id/commit/e45d9e970d327a5120ff9fb0c8d42df8af69bb38 introduced a bug with missing avatar in the header, this PR fixes it
> fix: avatar in header fix

- .github/ISSUE_TEMPLATE/bug.yml
- backend/internal/utils/email/email_service_templates.go
- frontend/src/routes/+layout.svelte
- frontend/src/routes/login/alternative/email/+page.svelte
> fix: correct misspellings

- backend/internal/controller/user_controller.go
- backend/internal/service/user_service.go
- frontend/src/lib/components/form/profile-picture-settings.svelte
- frontend/src/lib/services/user-service.ts
- frontend/src/routes/settings/account/+page.svelte
- frontend/src/routes/settings/admin/users/[id]/+page.svelte
Fixes: https://github.com/pocket-id/pocket-id/issues/346
> feat(profile-picture): allow reset of profile picture

- .github/workflows/backend-linter.yml
- backend/.golangci.yml
- backend/internal/bootstrap/db_bootstrap.go
- backend/internal/service/geolite_service.go
- backend/internal/service/ldap_service.go
- backend/internal/service/oidc_service.go
- backend/internal/service/user_service.go
- backend/internal/utils/email/composer.go
Hey there,
This PR is probably a bit random and unexpected, but as a big fan of the project I saw an opportunity and thought taking a few minutes to contribute would be helpful. I'm not sure if the maintainers are familiar with [golangci-lint](https://github.com/golangci/golangci-lint) or not so forgive me if I'm over explaining, but given that this project is starting to gain more popularity I thought you might benefit heavily from some automatic static analysis so you can save review time on common errors, vulnerabilities or style things you want to be consistent. 
I started this PR with a very small subset of the available linters for the Go backend to keep it small, but there are quite a lot you can enforce if you want. See [here](https://golangci-lint.run/usage/linters/). I'd be …
> Add basic static analysis for backend

- frontend/src/routes/settings/account/+page.svelte
Fixes: https://github.com/pocket-id/pocket-id/issues/421
> feat(onboarding): Added button when you don't have a passkey added.

- scripts/docker/entrypoint.sh
Patch would break setups like mine in case the env vars are defined already.
> fix: do not override XDG_DATA_HOME/XDG_CONFIG_HOME if they are already set

- backend/internal/controller/oidc_controller.go
- backend/internal/service/oidc_service.go
A few methods that were added recently did not receive the context from the request. This fixes it and ensures consistency.
> fix: pass context to methods that were missing it

- frontend/src/routes/settings/account/account-form.svelte
Fixes: https://github.com/pocket-id/pocket-id/issues/439
Missed a little part from the last PR. This small change should fix it.
> fix: last name still showing as required on account form

- backend/internal/controller/oidc_controller.go
- backend/internal/middleware/cors.go
> fix: handle CORS correctly for endpoints that SPAs need

- frontend/src/routes/authorize/+page.svelte
- frontend/src/routes/device/+page.svelte
- frontend/src/routes/login/+page.svelte
- frontend/src/routes/settings/account/+page.svelte
https://simplewebauthn.dev/docs/packages/browser#typeerror-cannot-read-properties-of-undefined-reading-challenge
> Update options API for simplewebauthn

- backend/internal/service/ldap_service.go
Fixes: https://github.com/pocket-id/pocket-id/issues/553
> fix: use ldapAttributeUserUsername for finding group members

- backend/internal/controller/oidc_controller.go
- backend/internal/dto/oidc_dto.go
- backend/internal/service/oidc_service.go
- frontend/messages/en-US.json
- frontend/src/lib/services/oidc-service.ts
- frontend/src/lib/types/oidc.type.ts
- frontend/src/routes/settings/admin/oidc-clients/oidc-client-list.svelte
Fixes: https://github.com/pocket-id/pocket-id/issues/527
> feat: show allowed group count on oidc client list

- backend/internal/common/errors.go
- backend/internal/dto/oidc_dto.go
- backend/internal/service/oidc_service.go
- frontend/messages/en-US.json
- frontend/src/lib/types/oidc.type.ts
- frontend/src/routes/settings/admin/oidc-clients/oidc-callback-url-input.svelte
- frontend/src/routes/settings/admin/oidc-clients/oidc-client-form.svelte
- tests/specs/oidc-client-settings.spec.ts
fixes: https://github.com/pocket-id/pocket-id/issues/538
> feat: auto detect callback url

- backend/internal/service/oidc_service.go
- frontend/messages/en-US.json
- frontend/src/routes/settings/admin/oidc-clients/oidc-callback-url-input.svelte
- frontend/src/routes/settings/admin/oidc-clients/oidc-client-form.svelte
> fix: don't use TOFU for logout callback URLs

- backend/internal/controller/audit_log_controller.go
- backend/internal/dto/audit_log_dto.go
- backend/internal/service/audit_log_service.go
- backend/resources/migrations/postgres/20250619115053_add_country_index.down.sql
- backend/resources/migrations/postgres/20250619115053_add_country_index.up.sql
- backend/resources/migrations/sqlite/20250619115053_add_country_index.down.sql
- backend/resources/migrations/sqlite/20250619115053_add_country_index.up.sql
- frontend/messages/en.json
- frontend/src/lib/components/form/searchable-select.svelte
- frontend/src/lib/types/audit-log.type.ts
- frontend/src/routes/settings/audit-log/global/+page.svelte
Fixes: https://github.com/pocket-id/pocket-id/issues/635
> feat: location filter for global audit log

- backend/internal/service/ldap_service.go
- backend/internal/service/ldap_service_test.go
> fix: support non UTF-8 LDAP IDs

- frontend/src/routes/login/alternative/code/+page.svelte
- frontend/src/routes/login/alternative/email/+page.svelte
Fixes #770 because inputs of type "email" do not use autocapitalization
> fix: set input type 'email' for email-based login

- backend/frontend/frontend_included.go
- backend/internal/bootstrap/router_bootstrap.go
- backend/internal/bootstrap/services_bootstrap.go
- backend/internal/controller/version_controller.go
- backend/internal/middleware/csp_middleware.go
- backend/internal/service/version_service.go
- backend/internal/utils/cache_util.go
- frontend/src/lib/services/version-service.ts
- frontend/src/routes/settings/+layout.ts
> feat: add CSP header

- backend/internal/bootstrap/application_images_bootstrap.go
> fix: do not treat certain failures in application images bootstrap as fatal

- backend/internal/dto/validations.go
- frontend/src/lib/utils/zod-util.ts
> fix: mark any callback url as valid if they contain a wildcard
