scripts/docker/create-user.sh
This is useful when running in environments like Kubernetes, where the orchestration system can take care of both setting your effective uid/gid, as well as filesystem permissions on the volume.
=> fix: if already not root, don't bother

backend/internal/service/geolite_service.go
- Added proper detection of Tailscale IPs using CGNAT range (100.64.0.0/10)
Source: https://tailscale.com/kb/1015/100.x-addresses
=> feat(geolite): add Tailscale IP detection with CGNAT range check 

docs/proxy-services.md
Adding the "groups" scope which is needed with the introduction of groups in pocket-id. Since this can be easily overseen it should be added to the example.
=> docs: Add "groups" scope to the oauth2-proxy sample configuration

backend/internal/controller/user_controller.go, backend/internal/controller/webauthn_controller.go
HTTPS is required for WebAuthn, so there's no downside to enabling this. And it prevents accidentally leaking an access token to the network in cleartext on an initial HTTP connection.
=> fix: always set secure on cookie

Dockerfile, backend/internal/dto/app_config_dto.go, backend/internal/model/app_config.go, backend/internal/service/app_config_service.go, backend/internal/service/geolite_service.go
This fixes a race condition while updating the mmdb, ensures the downloaded file is not corrupted and avoids pocket-id not being able to generate audit logs with locations due a bad database.
In github you cannot see the char replaced but this is the one.
=> fix: ensure the downloaded GeoLite2 DB is not corrupted & prevent RW race condition

frontend/src/routes/settings/admin/application-configuration/forms/app-config-email-form.svelte
This will fix https://github.com/stonith404/pocket-id/issues/158
Just runs the Save function if the Test Email button is pressed.
Also updated the button to say "Save and Send test email"
=> fix: add save changes dialog before sending test email

reverse-proxy/Caddyfile.trust-proxy
Current the Caddyfile.trust-proxy config only includes 0.0.0.0/0 which only includes IPv4 proxies.
Adding ::/0 (the equivalent of 0.0.0.0/0 for IPv6) allows for IPv6 proxies to be trusted. 
1) Ran docker image without modification on a IPv6 host with network_mode:host and a caddy server as a reverse proxy in front of the docker container [1].  
2) Attempt login and check audit logs for IP Address
3) Modify running docker container with `trusted_proxies ::/0` and reload caddy with changed Caddyfile
4) Attempt login and check audit logs for IP Address (see screenshot)
[1] Caddy site block on IPv6 enabled host
```
auth.example.com {
reverse_proxy localhost:8389
}
```
=> fix(caddy): trusted_proxies for IPv6 enabled hosts

docs/docs/client-examples/freshrss.md, docs/sidebars.ts
FreshRSS client documentation. I had come across an issue with setting up Pocket ID with FreshRSS due to case sensitivity with usernames. I added that warning to these docs in case anyone else has a similar issue.
=> Docs for adding Pocket ID to FreshRSS

docs/docs/client-examples/freshrss.md
Fixed the callback url for FreshRSS in the docs. It was missing '/i/oidc', as referenced here https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html.
=> docs: fix freshrss callback url

backend/.env.example, backend/internal/common/env_config.go
As discussed in #211, the backend now runs on 0.0.0.0 by default, and is overrideable through the `HOST` environment variable.
=> feat: update host configuration to allow external access

backend/internal/service/ldap_service.go
Added a missed check for syncing ldap users into ldap groups. we were not checking for the ldap_id when trying to add user into the group which could cause a sync fail.
=> fix: user linking in ldap group sync

backend/internal/controller/user_controller.go
Very minor fix to allow setting ones own profile picture.
When uploading a picture on `/settings/account`, a 500 is returned by the backend due to an invalid UUID.
Call the correct function to populate the UUID with ones own.
=> fix(account): call correct function to set own profile picture

backend/internal/service/email_service.go, backend/internal/utils/email/composer.go
add additional mail headers and do not encode realnames when they are only 7bit ascii chars
Fixes: #330
=> fix: pocket-id notify emails are considered as medium spam by rspamd

.env.example
The link in the example environment file didn't reflect the correct documentation link anymore
=> doc: update .env.example to reflect the new documentation location

backend/internal/controller/user_controller.go, backend/internal/job/file_cleanup_job.go, backend/internal/model/user.go, backend/internal/service/user_service.go, backend/internal/utils/string_util.go, backend/internal/utils/string_util_test.go
1. Ensures file descriptors are closed: changes in #406 meant that when reading the default picture, file descriptors would be left open
2. fixes ownership issue of the `defaultPicture` stream (previous code was potentially unsafe as the returned slice was valid only until the next buffer modification)
3. Fixes generation of initials when there are non-ASCII characters.
Fixup from #406
=> fix: ensure file descriptors are closed + other bugs

backend/internal/common/errors.go, backend/internal/controller/user_group_controller.go, backend/internal/service/ldap_service.go, backend/internal/service/ldap_service_test.go, backend/internal/service/user_group_service.go, backend/internal/service/user_service.go
This PR revises how errors are handled in the LDAP syncing service. I went through line-by-line to make sure that we treat errors consistently, and in most cases we should abort the sync and roll-back the changes in the DB (with some exceptions).
Should hopefully fix errors that were happening with syncing from LDAP, as some errors were simply logged while others causes failures.
=> fix: improve LDAP error handling

backend/internal/model/user.go
Fixes: https://github.com/pocket-id/pocket-id/issues/428
If no first or last name is found it uses the first two letters of the username to create the profile picture.
=> fix: profile picture empty for users without first or last name

scripts/docker/entrypoint.sh
Resolves the following errors when running rootless
<details><summary>Details</summary>
<p>
```json
[
{
"level": "error",
"ts": 1745222697.0053172,
"msg": "unable to create folder for config autosave",
"dir": "/.config/caddy",
"error": "mkdir /.config: permission denied"
},
{
"level": "warn",
"ts": 1745222697.0052032,
"logger": "tls",
"msg": "unable to get instance ID; storage clean stamps will be incomplete",
"error": "mkdir /.local: permission denied"
},
{
"level": "error",
"ts": 1745222697.0056646,
"logger": "tls",
"msg": "could not clean default/global storage",
"error": "unable to acquire storage_clean lock: creating lock file: open /.local/share/caddy/locks/storage_clean.lock: no such file or directory"
}
]
```
</p>
</details>
=> Fix rootless Caddy data and configuration

frontend/.prettierignore, frontend/src/hooks.server.ts, frontend/src/routes/+page.server.ts, frontend/src/routes/+page.ts, frontend/src/routes/lc/+page.ts, frontend/src/routes/lc/[code]/+page.ts, frontend/src/routes/login/alternative/code/+page.ts, frontend/src/routes/login/alternative/email/+page.server.ts, frontend/src/routes/login/alternative/email/+page.ts, frontend/src/routes/settings/+page.ts
Small refactor on the frontend: do not force redirects to happen on the server with `+page.server.ts`; use `+page.ts` instead, as they can happen on the client too
=> refactor: do not force redirects to happen on the server

backend/internal/controller/oidc_controller.go
Fixes #489.
Oops. I'm not entirely sure how this would be tested because it's so high up in the stack - needs HTTP afaict. Either way, it wasn't tested so far!
Good news is that this was only broken in the last day or two I guess and probably hasn't gotten to a release!
=> Fix incorrectly swapped refreshToken and accessToken

backend/cmd/main.go, backend/internal/bootstrap/bootstrap.go, backend/internal/bootstrap/e2etest_router_bootstrap.go, backend/internal/bootstrap/router_bootstrap.go, backend/internal/bootstrap/scheduler_bootstrap.go, backend/internal/bootstrap/services_bootstrap.go, backend/internal/job/geoloite_update_job.go, backend/internal/job/scheduler.go, backend/internal/service/app_config_service.go, backend/internal/service/email_service.go, backend/internal/service/geolite_service.go, backend/internal/utils/servicerunner.go, backend/internal/utils/servicerunner_test.go
Completes the work started in #482 to support graceful shutdown.
1. Introduces a ServiceRunner which manages long-running background services, running them until the context is canceled (and collecting errors)
2. Refactored `initBootstrap` and the GeoLite service's Run method to implement the ServiceRunner's Service interface
3. Moved the initialization of all "services" (not long-running) and the scheduler into their own function
=> refactor: complete graceful shutdown implementation and add service runner

backend/internal/bootstrap/db_bootstrap_test.go
Go's url.Values can be serialized in random order, which the test case didn't account for
Fixup from #530
=> fix: flaky unit test in db_bootstrap_test

backend/go.mod, backend/go.sum, backend/internal/job/analytics_job.go
1. Ensure there's a timeout in the HTTP request (using a context with timeout). The HTTP client passed doesn't have a timeout, so in certain cases the operation could block forever.
2. Skip registering the job entirely if analytics are disabled
3. Add a retry (with backoff) to handle transient failures
=> fix: small fixes in analytics_job

backend/internal/bootstrap/router_bootstrap.go, backend/internal/common/env_config.go
This is a supplement to #615.
It is difficult to set socket permissions externally, so add new option to set socket permissions internally.
=> feat: allow setting unix socket mode

.github/workflows/build-next.yml, .github/workflows/release.yml, Dockerfile, Dockerfile-distroless, backend/internal/bootstrap/bootstrap.go, backend/internal/cmds/healthcheck.go, backend/internal/cmds/root.go, docker-compose.yml
Fix #680
Adds a `-distroless` variant for the container image, which is based on `gcr.io/distroless/static-debian12:nonroot`
Because the distroless image doesn't have curl, in order to perform healthchecks I have added a new sub-command to the pocket-id binary `pocket-id healthcheck`, which performs a healthcheck on a running instance of Pocket ID. This is a simpler alternative to shipping the curl binary. (Note that curl is still bundled in the non-distroless image, for backwards compatibility)
=> feat: distroless container additional variant + healthcheck command

frontend/src/routes/settings/account/locale-picker.svelte
=> i18n: Fix inconsistent punctuation marks for the language name of zh-TW

backend/internal/middleware/rate_limit.go, backend/internal/service/audit_log_service.go, backend/internal/service/user_service.go
fixes #686 (for real)
The fix in #695 was not complete. It allowed the entry to be stored in the DB, but still caused failures when reading. This completes the fix.
Also fixes: authenticating with a one-time code did not create a log entry when the IP is empty
=> fix: login failures on Postgres when IP is null

backend/internal/controller/well_known_controller.go
Fixes: https://github.com/pocket-id/pocket-id/issues/790
Added both "plain" and "S256" from here https://datatracker.ietf.org/doc/html/rfc7636#section-6.2.2
=> feat: add support for `code_challenge_methods_supported`

frontend/static/robots.txt
Linked to #766
Serve a robots.txt which forbids both exploring and indexing by crawlers of all user agent
Hopefully this should stop indexing.
Note : If any other user gets their site indexed they can edit search results and delete them via the google search console if they own the domain under which their instance is served.
=> feat: add robots.txt to block indexing

backend/internal/bootstrap/db_bootstrap.go
Adding some additional log statements to the code creating database connections, to have some more debugging info.
This morning, I noticed that the pocket-id container in my server was not responding because something was wrong with the database (it probably wasn't up yet). Despite that, Pocket ID still started a server.
Logs here were not enough to understand what happened (they show a DNS resolution error, but it then didn't retry):
```
Aug 06 00:20:33 apps pocketid-pocketid[499293]: 2025/08/06 00:20:33 Server listening on 0.0.0.0:1411
Aug 06 00:20:33 apps pocketid-pocketid[499293]: 2025/08/06 00:20:33 INFO Starting job scheduler
Aug 06 00:20:33 apps pocketid-pocketid[499293]: 2025/08/06 00:20:33 INFO Starting job name=ClearAuditLogs id=a3df48ee-b481-4572-9fc1-4e81030891d5
Aug 06 …
```
=> chore: additional logs for database connections

backend/internal/service/oidc_service.go
feat to allow a user to specify a (Confidential + PKCE)  Client as a Public Client instead.
This is necessary for clients setup as confidential + PKCE authorization that do not protect client secrets properly.
One example is ownCloud OCIS ( Desktop/Android/IOS ) - the client secret is expected to be a hard coded/public value - see https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#client-ids-secrets-and-redirect-uris)
This is incorrect implementation by the service, however PocketID should ignore any client secret attached to a request for access from a Public Client as the spec does not expect this. This will allow support for these services as Public clients for now (once custom Client ID support is implemented).
=> fix: ignore client secret if client is public

backend/internal/service/webauthn_service.go
Partially reverts fe003b927ce7772692439992860c804de89ce424 . Calls to `CreateNewSignInWithEmail` accept a transaction, so they should be made before the tx is committed
=> fix: move audit log call before TX is committed

backend/resources/migrations/postgres/20250814121300_requires_reauthentication.up.sql
fixes #866
The column type for Postgres should be UUID
=> fix: wrong column type for reauthentication tokens in Postgres

backend/go.mod, backend/go.sum, backend/internal/bootstrap/db_bootstrap.go, backend/internal/bootstrap/observability_boostrap.go, backend/internal/bootstrap/router_bootstrap.go, backend/internal/common/env_config.go
This PR adds support for the `LOG_LEVEL` env variable. Additionally a few improvements were made:
- Replaced `github.com/samber/slog-gin` with `github.com/gin-contrib/slog`
- Removed `TextHandler` and use `tint.Handler` but without color if the output isn't a terminal 
Closes #294
=> feat: add support for `LOG_LEVEL` env variable

backend/internal/bootstrap/db_bootstrap.go, backend/internal/bootstrap/db_bootstrap_test.go, backend/internal/utils/testing/database.go
Low-priority fix, since it primarily impacts unit tests
When using an in-memory SQLite databases, if using multiple connections with cache=shared and there's a transaction blocking the database, another one will not wait and will fail to start right away
=> fix: do not use cache=shared for in-memory SQLite

backend/internal/bootstrap/router_bootstrap.go
Unix sockets cannot be created if the file already exists. The current socket file can be left behind if pocket-id closes ungracefully, either because of a crash or if the system loses power.
In those cases pocket-id fails to restart with the following error:
> failed to init router: failed to create unix listener: listen unix /pocketid/pocketid.sock: bind: address already in use
This PR removes the previous socket file, if it exists, before creating the router.
=> fix: remove previous socket file to prevent bind error
